services:
  - type: web
    name: alam-alabtal
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/settings
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: ECOTRACK_TOKEN
        sync: false
      - key: ECOTRACK_ENABLED
        value: "1"
      - key: ECOTRACK_BASE_URL
        value: https://anderson-ecommerce.ecotrack.dz
